Script started on Wed 29 Jan 2014 01:41:30 PM EST
]0;stephen@stephen_arch:~/documents/school-work/60-330/assignment1[?1034h[stephen@stephen_arch assignment1]$ gcc -Wall -Wextra seq_calc.c 
]0;stephen@stephen_arch:~/documents/school-work/60-330/assignment1[stephen@stephen_arch assignment1]$ time ./a.out 
3.141593

real	0m49.413s
user	0m49.393s
sys	0m0.003s
]0;stephen@stephen_arch:~/documents/school-work/60-330/assignment1[stephen@stephen_arch assignment1]$ gcc -Wall -Wextra proc_calc.c 
]0;stephen@stephen_arch:~/documents/school-work/60-330/assignment1[stephen@stephen_arch assignment1]$ time ./a.out 
3.141593

real	0m13.855s
user	0m0.060s
sys	0m0.350s
]0;stephen@stephen_arch:~/documents/school-work/60-330/assignment1[stephen@stephen_arch assignment1]$ exit
exit

Script done on Wed 29 Jan 2014 01:43:26 PM EST
