


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 26 22:24:09 EST 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Calc2Symbol {
  /* terminals */
  public static final int MULTI = 8;
  public static final int NUMBER = 9;
  public static final int SEMI = 6;
  public static final int EQUAL = 5;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int LPAREN = 3;
}

